language: shell
dist: focal

env:
  global:
    - CONTAINER_NAME=cs8898/android-fdroid-sdk

jobs:
  include:
    - env:
      - BUILD_TOOLS_VERSION=31.0.0
      - CONTAINER_TAG=latest
    - env:
      - BUILD_TOOLS_VERSION=31.0.0
      - CONTAINER_TAG=31.0.0
    - env:
      - BUILD_TOOLS_VERSION=30.0.2
      - CONTAINER_TAG=30.0.2

services:
  - docker

before_script:
  bash ./.travis/docker_login.sh

script:
  docker build --build-arg BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION -t $CONTAINER_NAME:$CONTAINER_TAG .

deploy:
  provider: script
  script: bash ./.travis/docker_push.sh
  on:
    branch: master

after_script:
  docker logout
