name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONTAINER_NAME: cs8898/android-fdroid-sdk

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BUILD_TOOLS_VERSION: "33.0.0"
            CONTAINER_TAG: "latest"
          - BUILD_TOOLS_VERSION: "33.0.0"
            CONTAINER_TAG: "33.0.0"
          - BUILD_TOOLS_VERSION: "31.0.0"
            CONTAINER_TAG: "31.0.0"
          - BUILD_TOOLS_VERSION: "30.0.2"
            CONTAINER_TAG: "30.0.2"
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build --build-arg BUILD_TOOLS_VERSION=${{ matrix.BUILD_TOOLS_VERSION }} -t $CONTAINER_NAME:${{ matrix.CONTAINER_TAG }} .
    - name: Docker Push
      run: docker push $CONTAINER_NAME:${{ matrix.CONTAINER_TAG }}
